name: Firebase App Distribution

on:
  pull_request:
    types:
      - labeled
    branches:
      - main
      - develop

jobs:
  distribute:
    name: Build & Upload to Firebase
    if: github.event.label.name == 'ReadyForTesting'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.0"
          channel: "stable"
          cache: true

      - name: Create google-services.json
        run: |
          cat > android/app/google-services.json << 'EOF'
          ${{ secrets.GOOGLE_SERVICES_JSON }}
          EOF

      - name: Create firebase_options.dart
        run: |
          cat > lib/firebase_options.dart << 'EOF'
          ${{ secrets.FIREBASE_OPTIONS }}
          EOF

      - name: Install dependencies
        run: flutter pub get

      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build APK
        run: flutter build apk --release

      - name: Create Service Account File
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > /tmp/service-account.json

      - name: Upload to Firebase App Distribution (Android)
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          serviceCredentialsFile: /tmp/service-account.json
          groups: flower-app-testers
          file: build/app/outputs/flutter-apk/app-release.apk
          debug: true