name: Firebase App Distribution

on:
  pull_request:
    types:
      - labeled
    branches:
      - main
      - develop

jobs:
  distribute:
    name: Build & Upload to Firebase
    if: github.event.label.name == 'ReadyForTesting'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.0"
          channel: "stable"
          cache: true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Create google-services.json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES" > android/app/google-services.json

      - name: Create firebase_options.dart
        env:
          FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTIONS }}
        run: echo "$FIREBASE_OPTIONS" > lib/firebase_options.dart

      - name: Create secrets.properties
        run: echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" > android/secrets.properties

      - name: Create secrets.xcconfig
        run: echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" > ios/Flutter/secrets.xcconfig

      - name: Install dependencies
        run: flutter pub get

      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Create Service Account File
        env:
          SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: echo "$SERVICE_ACCOUNT" > ${{ github.workspace }}/service-account.json

      - name: Build & upload to Firebase App Distribution
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          FIREBASE_ANDROID_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service-account.json
        run: bundle exec fastlane distribute_android
